#!/bin/bash

unset XDG_RUNTIME_DIR

singularity exec \
-B /home/jharriso/GitHub/seili-metabarcording:/home/jharriso/GitHub/seili-metabarcording \
-B /run:/run \
/home/jharriso/seili-singularity/seili-r.sif \
rstudio
