#!/bin/bash

unset XDG_RUNTIME_DIR

# run rstudio
singularity exec \
-B /home/jharriso/git/seili-metabarcoding:/home/jharriso/git/seili-metabarcoding \
-B /run:/run \
/home/jharriso/seili-singularity/seili-r.sif \
rstudio
